### ISSUE TITLE
Maven failed to execute goal on project

### ISSUE THREAD

**Issue by thegofar** [nahojkap/jahspotify#8]
Hi,  I am a complete novice and have given this a go but not really managed to solve this issue.

mvn clean -X install produces the following:

  <skip default-value="false">${mdep.skip}</skip>
  <stripVersion default-value="false">${mdep.stripVersion}</stripVersion>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <buildFilters default-value="${project.build.filters}"/>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <escapeString>${maven.resources.escapeString}</escapeString>
  <escapeWindowsPaths default-value="true">${maven.resources.escapeWindowsPaths}</escapeWindowsPaths>
  <includeEmptyDirs default-value="false">${maven.resources.includeEmptyDirs}</includeEmptyDirs>
  <outputDirectory default-value="${project.build.outputDirectory}"/>
  <overwrite default-value="false">${maven.resources.overwrite}</overwrite>
  <project default-value="${project}"/>
  <resources default-value="${project.resources}"/>
  <session default-value="${session}"/>
  <supportMultiLineFiltering default-value="false">${maven.resources.supportMultiLineFiltering}</supportMultiLineFilteri
ng>
  <useBuildFilters default-value="true"/>
  <useDefaultDelimiters default-value="true"/>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <basedir default-value="${basedir}"/>
  <buildDirectory default-value="${project.build.directory}"/>
  <classpathElements default-value="${project.compileClasspathElements}"/>
  <compileSourceRoots default-value="${project.compileSourceRoots}"/>
  <compilerId default-value="javac">${maven.compiler.compilerId}</compilerId>
  <compilerReuseStrategy default-value="${reuseCreated}">${maven.compiler.compilerReuseStrategy}</compilerReuseStrategy>

  <compilerVersion>${maven.compiler.compilerVersion}</compilerVersion>
  <debug default-value="true">${maven.compiler.debug}</debug>
  <debuglevel>${maven.compiler.debuglevel}</debuglevel>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <executable>${maven.compiler.executable}</executable>
  <failOnError default-value="true">${maven.compiler.failOnError}</failOnError>
  <forceJavacCompilerUse default-value="false">${maven.compiler.forceJavacCompilerUse}</forceJavacCompilerUse>
  <fork default-value="false">${maven.compiler.fork}</fork>
  <generatedSourcesDirectory default-value="${project.build.directory}/generated-sources/annotations"/>
  <maxmem>${maven.compiler.maxmem}</maxmem>
  <meminitial>${maven.compiler.meminitial}</meminitial>
  <mojoExecution>${mojoExecution}</mojoExecution>
  <optimize default-value="false">${maven.compiler.optimize}</optimize>
  <outputDirectory default-value="${project.build.outputDirectory}"/>
  <projectArtifact default-value="${project.artifact}"/>
  <showDeprecation default-value="false">${maven.compiler.showDeprecation}</showDeprecation>
  <showWarnings default-value="false">${maven.compiler.showWarnings}</showWarnings>
  <skipMain>${maven.main.skip}</skipMain>
  <skipMultiThreadWarning default-value="false">${maven.compiler.skipMultiThreadWarning}</skipMultiThreadWarning>
  <source default-value="1.5">1.6</source>
  <staleMillis default-value="0">${lastModGranularityMs}</staleMillis>
  <target default-value="1.5">1.6</target>
  <useIncrementalCompilation default-value="true">${maven.compiler.useIncrementalCompilation}</useIncrementalCompilation

>   <verbose default-value="false">${maven.compiler.verbose}</verbose>
>   <mavenSession default-value="${session}"/>
>   <session default-value="${session}"/>
> </configuration>
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Goal:          org.apache.maven.plugins:maven-resources-plugin:2.6:testResources (default-testResources)
> [DEBUG] Style:         Regular
> [DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
> <configuration>
>   <buildFilters default-value="${project.build.filters}"/>
>   <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
>   <escapeString>${maven.resources.escapeString}</escapeString>
>   <escapeWindowsPaths default-value="true">${maven.resources.escapeWindowsPaths}</escapeWindowsPaths>
>   <includeEmptyDirs default-value="false">${maven.resources.includeEmptyDirs}</includeEmptyDirs>
>   <outputDirectory default-value="${project.build.testOutputDirectory}"/>
>   <overwrite default-value="false">${maven.resources.overwrite}</overwrite>
>   <project default-value="${project}"/>
>   <resources default-value="${project.testResources}"/>
>   <session default-value="${session}"/>
>   <skip>${maven.test.skip}</skip>
>   <supportMultiLineFiltering default-value="false">${maven.resources.supportMultiLineFiltering}</supportMultiLineFilteri
> ng>
>   <useBuildFilters default-value="true"/>
>   <useDefaultDelimiters default-value="true"/>
> </configuration>
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Goal:          org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile)
> [DEBUG] Style:         Regular
> [DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
> <configuration>
>   <basedir default-value="${basedir}"/>
>   <buildDirectory default-value="${project.build.directory}"/>
>   <classpathElements default-value="${project.testClasspathElements}"/>
>   <compileSourceRoots default-value="${project.testCompileSourceRoots}"/>
>   <compilerId default-value="javac">${maven.compiler.compilerId}</compilerId>
>   <compilerReuseStrategy default-value="${reuseCreated}">${maven.compiler.compilerReuseStrategy}</compilerReuseStrategy>

  <compilerVersion>${maven.compiler.compilerVersion}</compilerVersion>
  <debug default-value="true">${maven.compiler.debug}</debug>
  <debuglevel>${maven.compiler.debuglevel}</debuglevel>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <executable>${maven.compiler.executable}</executable>
  <failOnError default-value="true">${maven.compiler.failOnError}</failOnError>
  <forceJavacCompilerUse default-value="false">${maven.compiler.forceJavacCompilerUse}</forceJavacCompilerUse>
  <fork default-value="false">${maven.compiler.fork}</fork>
  <generatedTestSourcesDirectory default-value="${project.build.directory}/generated-test-sources/test-annotations"/>
  <maxmem>${maven.compiler.maxmem}</maxmem>
  <meminitial>${maven.compiler.meminitial}</meminitial>
  <mojoExecution>${mojoExecution}</mojoExecution>
  <optimize default-value="false">${maven.compiler.optimize}</optimize>
  <outputDirectory default-value="${project.build.testOutputDirectory}"/>
  <showDeprecation default-value="false">${maven.compiler.showDeprecation}</showDeprecation>
  <showWarnings default-value="false">${maven.compiler.showWarnings}</showWarnings>
  <skip>${maven.test.skip}</skip>
  <skipMultiThreadWarning default-value="false">${maven.compiler.skipMultiThreadWarning}</skipMultiThreadWarning>
  <source default-value="1.5">1.6</source>
  <staleMillis default-value="0">${lastModGranularityMs}</staleMillis>
  <target default-value="1.5">1.6</target>
  <testSource>${maven.compiler.testSource}</testSource>
  <testTarget>${maven.compiler.testTarget}</testTarget>
  <useIncrementalCompilation default-value="true">${maven.compiler.useIncrementalCompilation}</useIncrementalCompilation

>   <verbose default-value="false">${maven.compiler.verbose}</verbose>
>   <mavenSession default-value="${session}"/>
>   <session default-value="${session}"/>
> </configuration>
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Goal:          org.apache.maven.plugins:maven-surefire-plugin:2.8.1:test (default-test)
> [DEBUG] Style:         Regular
> [DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
> <configuration>
>   <argLine>${argLine}</argLine>
>   <basedir default-value="${basedir}"/>
>   <childDelegation default-value="false">${childDelegation}</childDelegation>
>   <classesDirectory default-value="${project.build.outputDirectory}"/>
>   <debugForkedProcess>${maven.surefire.debug}</debugForkedProcess>
>   <disableXmlReport default-value="false">${disableXmlReport}</disableXmlReport>
>   <enableAssertions default-value="true">${enableAssertions}</enableAssertions>
>   <excludedGroups>${excludedGroups}</excludedGroups>
>   <failIfNoTests>${failIfNoTests}</failIfNoTests>
>   <forkMode default-value="once">${forkMode}</forkMode>
>   <forkedProcessTimeoutInSeconds>${surefire.timeout}</forkedProcessTimeoutInSeconds>
>   <groups>${groups}</groups>
>   <junitArtifactName default-value="junit:junit">${junitArtifactName}</junitArtifactName>
>   <jvm>${jvm}</jvm>
>   <localRepository>${localRepository}</localRepository>
>   <objectFactory>${objectFactory}</objectFactory>
>   <parallel>${parallel}</parallel>
>   <parallelMavenExecution default-value="${session.parallel}"/>
>   <perCoreThreadCount default-value="true">${perCoreThreadCount}</perCoreThreadCount>
>   <pluginArtifactMap>${plugin.artifactMap}</pluginArtifactMap>
>   <printSummary default-value="true">${surefire.printSummary}</printSummary>
>   <project default-value="${project}"/>
>   <projectArtifactMap>${project.artifactMap}</projectArtifactMap>
>   <redirectTestOutputToFile default-value="false">${maven.test.redirectTestOutputToFile}</redirectTestOutputToFile>
>   <remoteRepositories>${project.pluginArtifactRepositories}</remoteRepositories>
>   <reportFormat default-value="brief">${surefire.reportFormat}</reportFormat>
>   <reportsDirectory default-value="${project.build.directory}/surefire-reports"/>
>   <runOrder default-value="filesystem"/>
>   <session>${session}</session>
>   <skip default-value="false">${maven.test.skip}</skip>
>   <skipExec>${maven.test.skip.exec}</skipExec>
>   <skipTests default-value="false">${skipTests}</skipTests>
>   <test>${test}</test>
>   <testClassesDirectory default-value="${project.build.testOutputDirectory}"/>
>   <testFailureIgnore default-value="false">${maven.test.failure.ignore}</testFailureIgnore>
>   <testNGArtifactName default-value="org.testng:testng">${testNGArtifactName}</testNGArtifactName>
>   <testSourceDirectory default-value="${project.build.testSourceDirectory}"/>
>   <threadCount>${threadCount}</threadCount>
>   <trimStackTrace default-value="true">${trimStackTrace}</trimStackTrace>
>   <useFile default-value="true">${surefire.useFile}</useFile>
>   <useManifestOnlyJar default-value="true">${surefire.useManifestOnlyJar}</useManifestOnlyJar>
>   <useSystemClassLoader default-value="true">${surefire.useSystemClassLoader}</useSystemClassLoader>
>   <useUnlimitedThreads default-value="false">${useUnlimitedThreads}</useUnlimitedThreads>
>   <workingDirectory>${basedir}</workingDirectory>
> </configuration>
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Goal:          org.apache.maven.plugins:maven-jar-plugin:2.4:jar (default-jar)
> [DEBUG] Style:         Regular
> [DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
> <configuration>
>   <classesDirectory default-value="${project.build.outputDirectory}"/>
>   <defaultManifestFile default-value="${project.build.outputDirectory}/META-INF/MANIFEST.MF"/>
>   <finalName default-value="${project.build.finalName}">${jar.finalName}</finalName>
>   <forceCreation default-value="false">${jar.forceCreation}</forceCreation>
>   <outputDirectory default-value="${project.build.directory}"/>
>   <project default-value="${project}"/>
>   <session default-value="${session}"/>
>   <skipIfEmpty default-value="false">${jar.skipIfEmpty}</skipIfEmpty>
>   <useDefaultManifestFile default-value="false">${jar.useDefaultManifestFile}</useDefaultManifestFile>
> </configuration>
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Goal:          org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install)
> [DEBUG] Style:         Regular
> [DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
> <configuration>
>   <artifact default-value="${project.artifact}"/>
>   <attachedArtifacts default-value="${project.attachedArtifacts}"/>
>   <createChecksum default-value="false">${createChecksum}</createChecksum>
>   <localRepository>${localRepository}</localRepository>
>   <packaging default-value="${project.packaging}"/>
>   <pomFile default-value="${project.file}"/>
>   <skip default-value="false">${maven.install.skip}</skip>
>   <updateReleaseInfo default-value="false">${updateReleaseInfo}</updateReleaseInfo>
> </configuration>
> [DEBUG] =======================================================================
> [DEBUG] Could not find metadata jahspotify:libjahspotify:0.0.1-SNAPSHOT/maven-metadata.xml in local (C:\Users\cbarry.ATI
> UK.m2\repository)
> [DEBUG] Could not find metadata jahspotify:libjahspotify:0.0.1-SNAPSHOT/maven-metadata.xml in local (C:\Users\cbarry.ATI
> UK.m2\repository)
> [WARNING] The POM for jahspotify:libjahspotify:so:0.0.1-SNAPSHOT is missing, no dependency information available
> [DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=
> 3, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=2, ConflictIdSorter.co
> nflictIdCycleCount=0, ConflictResolver.totalTime=0, ConflictResolver.conflictItemCount=2, DefaultDependencyCollector.col
> lectTime=17, DefaultDependencyCollector.transformTime=0}
> [DEBUG] jahspotify:jahspotify-native-jar:jar:0.0.1-SNAPSHOT
> [DEBUG]    commons-logging:commons-logging:jar:1.0.4:compile
> [DEBUG]    jahspotify:libjahspotify:so:0.0.1-SNAPSHOT:compile
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] jahspotify-root ................................... SUCCESS [0.503s]
> [INFO] jahspotify-native-jar ............................. FAILURE [0.382s]
> [INFO] jahspotify-api .................................... SKIPPED
> [INFO] jahspotify-storage ................................ SKIPPED
> [INFO] jahspotify-web-common ............................. SKIPPED
> [INFO] jahspotify-services ............................... SKIPPED
> [INFO] jahspotify-web .................................... SKIPPED
> [INFO] jahspotify-libjahspotify .......................... SKIPPED
> [INFO] jahspotify-client ................................. SKIPPED
> [INFO] jahspotify-executable-war ......................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.974s
> [INFO] Finished at: Sat Oct 19 11:43:02 BST 2013
> [INFO] Final Memory: 8M/117M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project jahspotify-native-jar: Could not resolve dependencies for project jahspotify:j
> ahspotify-native-jar:jar:0.0.1-SNAPSHOT: Could not find artifact jahspotify:libjahspotify:so:0.0.1-SNAPSHOT -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project jahspotify-native-jar: Could n
> ot resolve dependencies for project jahspotify:jahspotify-native-jar:jar:0.0.1-SNAPSHOT: Could not find artifact jahspot
> ify:libjahspotify:so:0.0.1-SNAPSHOT
>         at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.j
> ava:220)
>         at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependenc
> yResolver.java:127)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
>         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
>         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
>         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
>         at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project jahspotify
> :jahspotify-native-jar:jar:0.0.1-SNAPSHOT: Could not find artifact jahspotify:libjahspotify:so:0.0.1-SNAPSHOT
>         at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:1
> 98)
>         at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.j
> ava:195)
>         ... 22 more
> Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact jahspotify:libjahspotify
> :so:0.0.1-SNAPSHOT
>         at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384
> )
>         at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:1
> 92)
>         ... 23 more
> Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact jahspotify:libjahspotify:s
> o:0.0.1-SNAPSHOT
>         at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
>         at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
>         at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367
> )
>         ... 24 more
> Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact jahspotify:libjahspotify:so:0.
> 0.1-SNAPSHOT
>         at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
>         ... 26 more
> [ERROR]
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :jahspotify-native-jar
> C:\Users\cbarry.ATIUK\Documents\Spotify\JahSpotifySource>

For reference, the directory of the root is landing here: "C:\Users\cbarry.ATIUK.m2\repository\jahspotify\jahspotify-root" it contains a file "maven-metadata-local.xml" I also have 0.0.1-SNAPSHOT containg:
'maven-metadata-local.xml'
'jahspotify-root-0.0.1-SNAPSHOT.pom' and '_remote.repositories' Any ideas or things to try would be very much appreciated, thanks!

**Comment by nahojkap** [comment]
Hi,

What version of Maven are you running?

Thanks,

Johan

**Comment by thegofar** [comment]
Hi Johan,

My windows folder is titled: 'apache-maven-3.1.1' I assume that is the version?

Annoyingly I have not got minGW working correctly.  I cannot compile helloworld.c at the moment - I will try and resolve that issue and hopefully the maven build will get further!

**Comment by nahojkap** [comment]
Hi,

Not tried it with Maven 3.1.1 yet - it has just been released.  Will let
you know when I have a chance to do so.

Johan

**Comment by thegofar** [comment]
I seriously suspect this issue is due to a failure to compile the C wrapper using minGW...
